# Generated by Django 3.2.5 on 2021-07-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracerapp', '0002_auto_20210725_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
