# Generated by Django 2.2.5 on 2021-03-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracerapp', '0002_auto_20210309_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='Solved',
            new_name='solved',
        ),
    ]
