# Generated by Django 2.2.5 on 2021-06-09 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracerapp', '0009_auto_20210603_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.ManyToManyField(related_name='read', to=settings.AUTH_USER_MODEL),
        ),
    ]
