# Generated by Django 2.2.5 on 2021-06-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('bugtracerapp', '0010_auto_20210609_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
